package gui;

import java.awt.Dialog;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;

/**
 *
 * @author Fox C
 */
public class SettingsWindow extends javax.swing.JPanel {

    /**
     * Creates new form SettingsWindow
     */
    public SettingsWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDivisionalSecretariatButton = new javax.swing.JButton();
        addPollingDivisionButton = new javax.swing.JButton();
        markDeathRecordsButton = new javax.swing.JButton();

        addDivisionalSecretariatButton.setBackground(new java.awt.Color(204, 204, 0));
        addDivisionalSecretariatButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        addDivisionalSecretariatButton.setForeground(new java.awt.Color(255, 255, 255));
        addDivisionalSecretariatButton.setText("Add Divisional Secretariat");
        addDivisionalSecretariatButton.setPreferredSize(new java.awt.Dimension(86, 31));
        addDivisionalSecretariatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDivisionalSecretariatButtonActionPerformed(evt);
            }
        });

        addPollingDivisionButton.setBackground(new java.awt.Color(0, 204, 204));
        addPollingDivisionButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        addPollingDivisionButton.setForeground(new java.awt.Color(255, 255, 255));
        addPollingDivisionButton.setText("Add Polling Division");
        addPollingDivisionButton.setPreferredSize(new java.awt.Dimension(86, 31));
        addPollingDivisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPollingDivisionButtonActionPerformed(evt);
            }
        });

        markDeathRecordsButton.setBackground(new java.awt.Color(0, 204, 51));
        markDeathRecordsButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        markDeathRecordsButton.setForeground(new java.awt.Color(255, 255, 255));
        markDeathRecordsButton.setText("Mark Death Records");
        markDeathRecordsButton.setPreferredSize(new java.awt.Dimension(86, 31));
        markDeathRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markDeathRecordsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addDivisionalSecretariatButton, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addComponent(markDeathRecordsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPollingDivisionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(addPollingDivisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addDivisionalSecretariatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(markDeathRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDivisionalSecretariatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDivisionalSecretariatButtonActionPerformed
        AddDivisionalSecretariats divisional = new AddDivisionalSecretariats();

        JDialog dialog = new JDialog(SwingUtilities.getWindowAncestor(this), "Divisional Secretariats", Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setContentPane(divisional);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_addDivisionalSecretariatButtonActionPerformed

    private void addPollingDivisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPollingDivisionButtonActionPerformed
        AddPollingDivisions polling = new AddPollingDivisions();

        JDialog dialog = new JDialog(SwingUtilities.getWindowAncestor(this), "Polling Divisions", Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setContentPane(polling);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_addPollingDivisionButtonActionPerformed

    private void markDeathRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markDeathRecordsButtonActionPerformed
        MarkDeathRecords deathRec = new MarkDeathRecords();

        JDialog dialog = new JDialog(SwingUtilities.getWindowAncestor(this), "Death Records", Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setContentPane(deathRec);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_markDeathRecordsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDivisionalSecretariatButton;
    private javax.swing.JButton addPollingDivisionButton;
    private javax.swing.JButton markDeathRecordsButton;
    // End of variables declaration//GEN-END:variables
}
