package gui;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.mysql.cj.Session;
import db.DatabaseConnector;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.JFrame;

/**
 *
 * @author Fox C
 */
public class SignIn extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignIn.class.getName());

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }

    //Session
    public class Session {
        public static String nic;
        public static String firstName;
        public static String lastName;
        public static String dbUserName;
        public static String systemUserId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        signIn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alumini System  Sign In");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        userNameField.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        userNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userNameFieldKeyReleased(evt);
            }
        });
        getContentPane().add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 283, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        passwordField.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        passwordField.setPreferredSize(new java.awt.Dimension(64, 29));
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 283, 30));

        signIn.setBackground(new java.awt.Color(0, 102, 0));
        signIn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        signIn.setForeground(new java.awt.Color(255, 255, 255));
        signIn.setText("Sign In");
        signIn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });
        getContentPane().add(signIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 411, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/signInbg.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameFieldKeyReleased
        if (evt.getKeyCode() == 10) {
            passwordField.grabFocus();
        } else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN) {
            passwordField.grabFocus();
        }
    }//GEN-LAST:event_userNameFieldKeyReleased

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
        if (evt.getKeyCode() == 10) {
            signInActionPerformed(null);
        } else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP) {
            userNameField.grabFocus();
        }
    }//GEN-LAST:event_passwordFieldKeyReleased

    //Sign In code
    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed

        String userName = userNameField.getText();
        String password = String.valueOf(passwordField.getPassword());

        if (userName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Username to continue", "Warning", JOptionPane.WARNING_MESSAGE);
            userNameField.grabFocus();
        } else if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Password to continue", "Warning", JOptionPane.WARNING_MESSAGE);
            passwordField.grabFocus();
        } else {

            try {
                String sql = "SELECT * FROM `system_user` WHERE `user_name` = ? AND `password` = ?";
                ResultSet resultSet = DatabaseConnector.executeQueryWithParams(sql, userName, password);

                if (resultSet.next()) {
                    String nic = resultSet.getString("nic");
                    String firstName = resultSet.getString("first_name");
                    String lastName = resultSet.getString("last_name");
                    String dbUserName = resultSet.getString("user_name");
                    String systemUserId = resultSet.getString("id");
                    Session.nic = nic;
                    Session.firstName = firstName;
                    Session.lastName = lastName;
                    Session.dbUserName = dbUserName;
                    Session.systemUserId = systemUserId;

                    Dashboard dashboard = new Dashboard();
                    dashboard.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Please enter valid user details", "Cannot SignIn", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_signInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatDarculaLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignIn().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signIn;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
